### ISSUE TITLE
SATA problem on MeleA1000

### ISSUE THREAD

**Issue by nik0** [linux-sunxi/linux-sunxi#40] opened 2012-06-19 13:13 UTC
I succeeded to compile and start my own kernel, using the branch allwinner-v3.0-
android-v2 ...
But when I install the sata module (sw_ahci_platform) I have this error:

```
<6>ata1: EH complete
<3>ata1: exception Emask 0x10 SAct 0x0 SErr 0x4000000 action 0xe frozen
ata1: exception Emask 0x10 SAct 0x0 SErr 0x4000000 action 0xe frozen
<3>ata1: irq_stat 0x00000040, connection status changed
<3>ata1: SError: { DevExch }
<4>ata1: limiting SATA link speed to 1.5 Gbps
<6>ata1: hard resetting link
<6>ata1: SATA link down (SStatus 1 SControl 310)
<6>ata1: EH complete
<3>ata1: exception Emask 0x10 SAct 0x0 SErr 0x4000000 action 0xe frozen
<3>ata1: irq_stat 0x00000040, connection status changed
<3>ata1: SError: { DevExch }
```

I checked the internet, some guys report a cable error, but when I boot on 
Android I get this:

```
sw_ahci sw_ahci.0: controller can't do PMP, turning off CAP_PMP
sw_ahci sw_ahci.0: forcing PORTS_IMPL to 0x1
sw_ahci sw_ahci.0: AHCI 0001.0100 32 slots 1 ports 3 Gbps 0x1 impl platform mode
sw_ahci sw_ahci.0: flags: ncq sntf pm led clo only pio slum part ccc 
scsi0 : sw_ahci_platform
ata1: SATA max UDMA/133 irq_stat 0x00400040, connection status changed irq 56
ata1: SATA link up 3.0 Gbps (SStatus 123 SControl 300)
ata1.00: native sectors (2) is smaller than sectors (1953525168)
ata1.00: ATA-8: ST1000LM024 HN-M101MBB, 2AR10002, max UDMA/133
ata1.00: 1953525168 sectors, multi 0: LBA48 NCQ (depth 31/32)
ata1.00: configured for UDMA/133
```

Any suggestions ?

Thanks and regards,

Nik0

**Comment by amery** [comment] 2012-06-19 13:21
can you try the `lichee-3.0.8-sun4i` branch?

**Comment by nik0** [comment] 2012-06-20 07:11
Thanks for the advice, but seems to have the same problem ...

**Comment by amery** [comment] 2012-06-20 07:22
that's good an bad. good because it means we didn't break it, bad because we don't have a "good version" to start bisecting

**Comment by nik0** [comment] 2012-06-21 08:06
Oups, I did the test too quickly and in fact I did not test the lichee-3.0.8-sun4i branch.
I recompile the new branch but the boot process is stuck just after the RAM size is logged. I have to do some extra tests.

**Comment by cnxsoft** [comment] 2012-07-04 07:41
Not exactly related, but somebody posted this comment on my blog about SATA:
"Module sw_ahci_platform.ko not loading automatically,
If you want the module SATA loading automatically then edit /etc/modules and at the sw_ahci_platform in a line.
But in this case does not always happen automount, and build a new kernel with built-in SATA module, now all ok."

So SATA does work for some people (using 21/6/2012 kernel), but if you load the module in /etc/modules, it will sometimes fail to automount (I guess he's put it in fstab). Should we build SATA inside the kernel by default instead, or is there a better way to load the module at boot time?

**Comment by nik0** [comment] 2012-07-09 08:06
Thanks for the info.
When you talk about the 21/06/12 kernel, which branch your are talking about ?
I tried to add the module in /etc/modules and I also tried to include the module in the kernel (changing the config file), but the result is always the same ...

**Comment by cnxsoft** [comment] 2012-07-09 08:32
The default branch, I think allwinner-v3.0-android-v2. I've seen somebody has the exact same problem (http://www.cnx-software.com/2012/06/22/ubuntu-12-04-server-armhf-image-for-mele-a1000a2000/comment-page-4/#comment-9677). I suppose it may also depend on the hard drive used, but if if works with the "android" kernel, we should manage to make it work for Linux as well.

**Comment by hyenadog** [comment] 2012-07-25 22:23
Hi, I have compiled my own melea1000 kernel  3.0.38 (allwinner-v3.0-android-v2) and wheezy ROOTFS .. and SATA doesnt work ...

more specifically (testing with an old 60GB Toshiba SATA 2.5 HD):
1. after boot and before inserting sata drive caddy 

modprobe sw_ahci_platform yields

```
<7>libata version 3.00 loaded.
[   33.560000] libata version 3.00 loaded.
err: gpio count < =0 ,gpio_count is: 0 
[   33.660000] err: gpio count < =0 ,gpio_count is: 0 
<6>sw_ahci sw_ahci.0: controller can't do PMP, turning off CAP_PMP
[   33.680000] sw_ahci sw_ahci.0: controller can't do PMP, turning off CAP_PMP
<4>sw_ahci sw_ahci.0: forcing PORTS_IMPL to 0x1
[   33.700000] sw_ahci sw_ahci.0: forcing PORTS_IMPL to 0x1
<6>sw_ahci sw_ahci.0: AHCI 0001.0100 32 slots 1 ports 3 Gbps 0x1 impl platform mode
[   33.720000] sw_ahci sw_ahci.0: AHCI 0001.0100 32 slots 1 ports 3 Gbps 0x1 impl platform mode
<6>sw_ahci sw_ahci.0: flags: ncq sntf pm led clo only pio slum part ccc 
[   33.740000] sw_ahci sw_ahci.0: flags: ncq sntf pm led clo only pio slum part ccc 
<6>scsi0 : sw_ahci_platform
[   33.760000] scsi0 : sw_ahci_platform
<6>ata1: SATA max UDMA/133 mmio [mem 0x01c18000-0x01c18fff] port 0x100 irq 56
[   33.780000] ata1: SATA max UDMA/133 mmio [mem 0x01c18000-0x01c18fff] port 0x100 irq 56
```

so it looks like it may be a driver or config issue with  "err: gpio count < =0 ,gpio_count is: 0" being a useful piece of info
1. Once i insert the SATA caddy&drive  i get the repeating :

```
<6>ata1: SATA link down (SStatus 0 SControl 300)
[   34.170000] ata1: SATA link down (SStatus 0 SControl 300)
root@MELESVR:~# <3>ata1: exception Emask 0x10 SAct 0x0 SErr 0x4000000 action 0xe frozen
[   49.690000] ata1: exception Emask 0x10 SAct 0x0 SErr 0x4000000 action 0xe frozen
<3>ata1: irq_stat 0x00000040, connection status changed
[   49.710000] ata1: irq_stat 0x00000040, connection status changed
<3>ata1: SError: { DevExch }
[   49.720000] ata1: SError: { DevExch }
<6>ata1: hard resetting link
[   49.730000] ata1: hard resetting link  
```

hope it helps .. rgds

ian

**Comment by hyenadog** [comment] 2012-07-25 22:46
this looks like it may be relevant :

https://github.com/amery/linux-allwinner/issues/11#issuecomment-5764776

rgds

ian

... update -> I connected the 60GB 2.5 SATA to an external power supply and used a known good cable to connect directly to the sata connector on the board so presumably this rules out power supply and dodgy sata connectors ... i also tried backing out the GPIO change referred to in the above link and recompiling the kernel with no difference in the error messages/behaviour at all

**Comment by cnxsoft** [comment] 2012-07-26 02:31
Since it works for some people and not other, I wonder if it could be related to script.bin.

**Comment by hyenadog** [comment] 2012-07-26 03:34
i suspect that people are using kernels compiled from different git branches (some with sw sata drivers that work in that branch and some that dont) ... the sw_ahci_platform drivers (red hat sourced) were i think just "taken in" to the allwinner-v3.0-android-v2 and i did notice in another GIT branch what looked like more specific (and totally different) A10   sw_ahci_platform drivers  ... i tried swapping over the .c and .h drivers to these and recompiling the kernel but the driver wouldnt load .. but thats probably my lack of knowledge on all things linux & compiling ;-)

if you fancy a look :

https://github.com/amery/linux-allwinner/blob/allwinner-v3.0-android/drivers/ata/sw_ahci_platform.c

https://github.com/amery/linux-allwinner/blob/allwinner-v3.0-android/drivers/ata/sw_ahci_platform.h

I.R.O. script.bin ... i had a look at this and i cant see what you could change in any way that would impact on SATA or SCSI or PATA etc ... underneath SATA =1 there is another item (unset) and i tried setting this alternately to 0 and 1 (and fex->bin) and it made no diff at all ... so i would be surprised if it was this (though something could be omitted especially as these were SATAless tablet script.bin's originally)  ... i think the killer though is that when people default to the original "Rhombus" script.bin which reportedly "works" on earlier branches then they see the same errors we all seem to be seeing .. my gut feeling is that the drivers need to be looked at for this branch - 

It would be good to get a working "rig" as a basemark though then probably best to get someone that does have working SATA (so thats with a real sata drive plugged in)  to confirm branch, linux version, rootfs, script.bin, and a copy of the sata drivers  & make/model of HD etc and the people that hopefully know a bit more will find it a bit easier to get to the bottom of it .

**Comment by amery** [comment] 2012-07-26 09:10
@hyenadog `err: gpio count < =0 ,gpio_count is: 0` is very clear, your script.bin doesn't have the sata pins configured. use the script.bin of your device, not from any random source.

**Comment by amery** [comment] 2012-07-26 09:18
@hyenadog also, as Qware's release didn't have a sata driver we are still carrying the one from 2.6.36, that means the driver on every branch is identical.

**Comment by amery** [comment] 2012-07-26 13:09
**update**: I just realized I get that `err: gpio count < =0 ,gpio_count is: 0` too, and my sata works fine. /me puzzled

**Comment by hyenadog** [comment] 2012-07-26 13:59
hi .. i used the script bin (generated from the Rhombus site compilation script) .. just switched off all video and wifi/bluetooth in it  (so i get close to 512MB in headless)  ... no problem trying an alternative .. do you have a link to what you consider a good fex or bin and ill have a bash a little later on ...

**Comment by amery** [comment] 2012-07-26 14:01
@hyenadog can you try with the disk connected before power up?

**Comment by hyenadog** [comment] 2012-07-26 22:51
hi .. sorry been out all evening collecting my Olympic tickets :-)

yes i tried this yesterday and got the same sata connection rebooting & messages after issuing a modprobe sw_ahci_platform 
 (the only way a newbie like me can think of the check sata is operational)

just tried it again to make sure and the same once i issue the modeprobe

... the other thing i thought of is that people are using different defconfigs and maybe there is some kind of conflict there ? .. whats the MINIMUM under the various SCSI categories (and elsewhere) that appears in a SATA working defconfig (of this kernel/branch)  ... i can delete everything else under SCSI and elsewhere (and add anything missing) and try again

i know i'm gonna get people bitching about editing defconfigs .. but if they desire to give me the detailed menus/options in menu config the various items fall then i will have a try at this as well to keep them happy :-)

thx

ian

**Comment by hyenadog** [comment] 2012-08-03 00:33
Hi .. after doing a recent kernel rebuild on checking the Kernel build log I see what appears like missing files :

drivers/ata/sw_ahci_platform.c:36:26: fatal error: mach/gpio_v2.h: No such file or directory
compilation terminated.

rgds

ian

**Comment by amery** [comment] 2012-08-03 12:23
@hyenadog `drivers/ata/sw_ahci_platform.c` doesn't include `mach/gpio_v2.h` since 2.6.36... what branch are you building???

**Comment by hyenadog** [comment] 2012-08-03 19:27
hi,

I use a script to generate the kernels, so i just pulled in the GIT branch the once about a week or so ago (allwinner-v3.0-android-v2) .. kernel is 3.0.38   ... perhaps something has gone up the swanny somewhere, i'll try and refresh my local GIT store ... 

yep after refreshing my local GIT store and recompiling the ahci kernel missing file error message has gone - weird

back to the perpetual rebooting SATA link now ... i think i'll try messing around with a few items in the kernel config and see if that makes a difference.

thx

ian

**Comment by hyenadog** [comment] 2012-08-10 18:39
Hi,

done some testing and quite a trial and error elimination on kernel config and eliminated it as an issue (with my newbie knowledge of kernel  config) other than the allwinner sata driver having to be activated .. 

googled quite a bit and interestingly libata/etc had an issue at around kernel 2.6 where hot plug was brought in and caused the same errors with certain drives (WD an example) .. coincidently I have tried a hotplug WD 640MB 2.5 SATA as well and saw the same errors as the old toshiba sata drive ive been using for testing   ... these issues were dealt with i think on the iMX53 for example by patching libata/etc .. and they state an emergency workaround of depending on which article you read adding  libata.force=norst, libata.force=noncq, libata.noacpi=1 to kernel options ... I tried to add these to boot.cmd/convert to boot.scr .. but i think probably my lack of knowledge on the format of these commands screwed it up :
boot.cmd:
setenv bootargs console=ttyS0 root=/dev/mmcblk0p1 extra 'rootfstype=ext4 rootwait mem=512M libata.force=norst'
ext2load mmc 0 0x43000000 boot/script.bin
ext2load mmc 0 0x48000000 boot/uImage
bootm 0x48000000

## heres an excerpt of a Mx53 post 

-- don't ask how many times I re-compiled the kernel.

I did trace the problems I having to the ahci code in the kernel not properly handling an ahci CONINIT event generated by my WD5000BEVT drive.  Seems this drive has extra SATA features implemented so that it can be used in hot-plug arrays and these features aren't recognized by the kernel driver so it just seems to shut down the drive and ignore it.  The other SATA drive that I do have working with the kernel doesn't implement the extra features so the kernel is happy.  Presumably these problems were fixed in later kernels and the patches didn't make it into Freescales 2.6.35.3 branch.  On the other hand, the kernel might be fine and the firmware in the drive isn't conforming to the ahci specs, but I think that wold cause problems with the drive on other systems.  I'm going to keep looking into this as I do want to get my 500GB SATA drive working with the iMX53 Quick Start.

So, if you add the following kernel option during installation and afterwards for every boot, the disk seems to work quite well    libata.force=norst

So here I am .. ive come to the conclusion that its either a duff sata board connection on my mele (i should really see if it works in a stock old mele android to eliminate this) or a libata and/or allwinner sata driver which needs updating to cope with common sata drive commandsets

hope it helps ..

rgds

ian

**Comment by hyenadog** [comment] 2012-08-25 02:08
.. tested now with mele's latest android 4 and both (all my) 2.5 sata drives that will not work with linux work just fine with android .. i wonder what mele have used in their android 4 for config and sata drivers ?

Also tested with the cubie hipboi (non mele) compiled version of android 4 (which presumably used similar Sata drivers and config to what's available here for Linux) and both drives failed to be recognised in any way and generate the usual errors.  

So the conclusion is there is a Sata config or driver issue in the current a10 Linux source on git which prevents some sata drives operating .. Looks like mele in android 4 have sorted it out

**Comment by stevenvo** [comment] 2012-09-16 06:28
Just tested adding libata.force=norst but no hope :(

**Comment by hyenadog** [comment] 2012-09-17 22:13
hi ... looks like the solution is here ... needs someone amery ?  to test and commit ... 

http://forum.doozan.com/read.php?6,9597

**Comment by amery** [comment] 2012-09-18 07:20
looking at the patch against https://github.com/amery/linux-allwinner/blob/allwinner-v3.0-android-v2/arch/arm/mach-sun4i/clock/clock.c#L165 the problem is on C ver ICs when USE_PLL6M_REPLACE_PLL4 is defined.

what troubles me is that the whole point of all that chunk is to overclock that particular case, from 600MHz to 980MHz, so removing one of the three clock rate changes for that case feels wrong.

**Comment by amery** [comment] 2012-09-18 07:35
looking at our sw_get_ic_ver() implementation C is basically a blind fallback, when it's not A or B. ... may it be possible that your is not really C but... D, and we don't know how to deal with those?

**Comment by guillaumef** [comment] 2012-09-18 08:15
hi, thanks to hyena to have spread my patch here.
My first post was seeking for more testing on this patch.
Amery, i think you are right about a possible ~D version not identified by sw_get_ic_ver().
The C version is the fallback...
But this patch only affects PLL6 clock and properly corrects the issue on my twelve mele a2000.
The sata2 is stable, no more non-stop reset and no more 1.5Gbps reset.
This underclocking (... 600MHz is the original clock of A/B version) does not seems to harm a bit.
More extensive testing on VersC all around could be a wise decision.

**Comment by amery** [comment] 2012-09-18 08:22
@guillaumef hi, nice discovery. I don't know about these things, neither we have real documentation (@hno has more experience with A10's clocks), but my wonder is basically that if we underclock PLL6 to revA/B rates, shouldn't we do the same for PLL6M and PLL62 too? they seem tightly connected in the code.

**Comment by guillaumef** [comment] 2012-09-18 08:37
Reverting all the clocks to the VersB... ;)
I'm not sure and is a bit more risky than just correcting the sata pll. I have no clue on this. I found the bug by dismantling the whole sw_ahci_platform init process between a working mele a2000 (which revealed itself to be a VersB) and failing a2000 (VersC).
The clock change could be tested but as far as i know, the a10 VersC seems perfectly stable with just the PLL6 rate change.

**Comment by amery** [comment] 2012-09-18 12:50
a shrinked version of the patch (not killing psedo documentation) is

``` diff
diff --git a/arch/arm/mach-sun4i/clock/clock.c b/arch/arm/mach-sun4i/clock/clock.c
index 4df915e..d092e71 100755
--- a/arch/arm/mach-sun4i/clock/clock.c
+++ b/arch/arm/mach-sun4i/clock/clock.c
@@ -178,7 +178,7 @@ int clk_init(void)

         /* sata pll set to 960mhz for c ver. */
         tmpSclk = &ccu_sys_clk[AW_SYS_CLK_PLL6];
-        #if(USE_PLL6M_REPLACE_PLL4)
+        #if 0 /*(USE_PLL6M_REPLACE_PLL4) -- unstable */
         tmpSclk->clk->rate  = 960000000;
         #else
         tmpSclk->clk->rate  = 600000000;
```

but it still feels wrong :-(

**Comment by guillaumef** [comment] 2012-09-18 13:11
Stock Android 2 or ICS are working fine with sata ... like linux-allwinner with this patch ;-)

perhaps they have found a more elegant solution... like simply patch sw_get_ic_ver and creating a VersD to switch more properly between different A10 inits. No way to know.

**Comment by hno** [comment] 2012-09-18 16:46
tis 2012-09-18 klockan 06:11 -0700 skrev Guillaume Fougnies:

> Stock Android 2 or ICS are working fine with sata ... like
> linux-allwinner with this patch ;-)

Looking at the code I think the right path is to not define that define.
That leaves PLL6 for SATA use only, using PLL4 for the other clock
functions.

The PLL6M and PLL62 clocks are nothing more than clock signals taken
from different parts/stages of PLL6, not independent clocks. Looks very
unwise to try to tune them separately, and the number of possible values
is very limited as the parts/stages all depend on each other.

A preleminary guess without analyzing the clock tree changes in full
detail is that the define is there to reduce power a bit by turning off
PLL4.

Regards
Henrik

**Comment by hyenadog** [comment] 2012-09-18 17:33
Guillaume,

hi

hipboi's (aka Tom Cubie) android 4 for the mele doesnt work with SATA wheras Mele's android 4 works fine with all sata drives .. sounds like mele has sorted it with a patch (what they are patching may very well be a newer codebase) 

as his daytime job is with allwinner and on the side hes been flogging the mele boxes for export (and now an a10 board with sata as well) as he really needs to ensure SATA is working so perhaps he has some input to contribute from the "horses mouth" (mele or allwinner or his oem) as they say 

... in this group as well probably fall Olimex in time as they planned to release an A10 with SATA board as well (they are usually high quality open products with decent support)

rgds

ian

**Comment by guillaumef** [comment] 2012-09-18 18:27
Disabling USE_PLL6M_REPLACE_PLL4 corrects the sata reset too, indeed it is setting the right clock rate in PLL6 but it keeps the PLL4 clock On...
So my patch is wrong, it makes the PLL4 (replaced by the PLL6) run at 600... which should be at 960.

What is the purpose of PLL4 -> VE-CLK-OUT (sorry if the answer is somewhere, i didn't find it ;-) ?

This story of 'define' looks a bit stupid to me... VersC A10 should be able to manage PLL6 at 960 making it possible to disable PLL4 and save a tiny bit of power. But PLL6 at 960 makes the sata fail so the whole trick (which is creating a far less straightforward code) is completely useless ? ..
i don't get it ;)

PS: Hyena, before searching for the sata bug, i asked to tom. He seemed to have no clue except the sata cable, the script.bin or the disk kind (it was ~ 2 weeks ago). But perhaps with this story, he could investigate a bit more ?

**Comment by amery** [comment] 2012-09-19 07:11
so we agree on this as a temporal solution? @hipboi doesn't work for Allwinner anymore, but hopefully he can still ask his former colleagues about it.

``` diff
diff --git a/arch/arm/mach-sun4i/include/mach/aw_ccu.h b/arch/arm/mach-sun4i/include/mach/aw_ccu.h
index 7af508e..a797ff3 100755
--- a/arch/arm/mach-sun4i/include/mach/aw_ccu.h
+++ b/arch/arm/mach-sun4i/include/mach/aw_ccu.h
@@ -27,10 +27,11 @@
 #include <linux/kernel.h>
 #include <linux/string.h>

+#if 0  /* PLL6M is SATA only, but this makes A10rC unstable */
 /* define if need use pll6 to take the place of pll4,
    this definition is significative on C ver. only */
 #define USE_PLL6M_REPLACE_PLL4      (1)
-
+#endif

 /* define clock error type      */
 typedef enum __AW_CCU_ERR
```

**Comment by guillaumef** [comment] 2012-09-19 08:28
Looks good to me.

Found here, seems the original commit from kevin ?
https://github.com/allwinner/linux-2.6.36/commits/lichee-dev/arch/arm/mach-sun4i/clock/clock.c

**Comment by amery** [comment] 2012-09-19 08:32
@guillaumef does https://github.com/allwinner/linux-2.6.36/commit/b975f3aa321c0bfc82b91cf52366eb05fdaa8bfb fix the problem?

**Comment by guillaumef** [comment] 2012-09-19 08:40
No, this commit just correct another clock error from the previous post (https://github.com/allwinner/linux-2.6.36/commit/6dc141c7d6fbd7f2ff93fe6c7fea09a3f61659ea).
This post is the creation of the PLL6M_REPLACE_PLL4.
I just don't understand the purpose of introducing this trick around PLL4/PLL6.
Perhaps there's a good reason for this... it's bothering me.

**Comment by hno** [comment] 2012-09-19 10:46
The define reroutes PLL6 to be used where PLL4 is otherwise used, which
is quite many functions. PLL4 is consequently disabled in such
configuration.

By not having the define set PLL4 is configured at 960MHz as usual, and
PLL6 is configured for use by SATA only.

What is unclear is why they did this change in REVC.

Regards
Henrik

ons 2012-09-19 klockan 00:11 -0700 skrev Alejandro Mery:

**Comment by hno** [comment] 2012-09-19 19:10
ons 2012-09-19 klockan 01:40 -0700 skrev Guillaume Fougnies:

> Perhaps there's a good reason for this... it's bothering me.

I have sent a question regarding this to Allwinner. Lets see what they
answer.

Regards
Henrik

**Comment by amery** [comment] 2012-09-24 16:17
We just got a fix from the cubie team. see https://groups.google.com/d/topic/linux-sunxi/eu3xw-nsxoM/discussion ... can you test?

**Comment by amery** [comment] 2012-09-24 16:20
http://sprunge.us/HPSH the raw diff.

**Comment by guillaumef** [comment] 2012-09-24 18:33
Hum... ok it's working ... by always setting the PLL6 clock to 100Mhz.

<code>
    /\* init pll6 frequency _/
    tmpFreq = 1200;
    .... // No modification on tmpFreq
    ...
    if ((tmpFreq/100)_100 == tmpFreq) {
     /\* set clock to 100Mhz _/
     tmpSclk->clk->rate  = 100 \* 1000000;
    } else {
     /_ not divide the clock */
     tmpSclk->clk->rate  = (tmpFreq/6) \* 1000000;
    }
</code>

Depending on the fact the previous tmpFreq modulo 100 = 0 which is always true because is forced to 1200...
I don't get it.

**Comment by amery** [comment] 2012-09-24 18:36
@guillaumef can you reply on the ML so the author receives the comments too?

**Comment by guillaumef** [comment] 2012-09-25 23:47
No news from the ML and double posted on it.

I tried to decompose the process avoiding the useless conditions:

If (VersC && Disable_PLL4)
 Turn off the PLL4
else
  PLL4 < 960 MHz

PLL6 < 1200 MHz

PLL6M < 100 MHz

PLL62 < 600 MHz

APB1 (Low speed Advanced Peripherial Bus) sourced to OSC24M (24MHz oscillator)
APB1 < 24 MHz

the difference with the current github is:
- PLL6 set to 1200MHz versus 960MHz for VersC and 600MHz for others
- PLL6M set to 100MHz versus 160MHz for VersC (already 100MHz for others)
- PLL62 set to 600MHz versus 480MHz for VersC and 300MHz for others
- the trick with APB1

PLL4 stays the same way. Off with USE_PLL6M_REPLACE_PLL4 and set to 960 otherwise.

Perhaps i have misread.
Do someone have an opinion?
Is it not risky for NotVersC ?

I will try some test tomorrow on these new values for VersC... avoiding the modification on NotVersC.

**Comment by guillaumef** [comment] 2012-10-08 19:29
Something ?
I'm a bit sad to see, 21 days after getting a working patch, to read some users stuck with the same issue still looking for a working kernel.
Sorry for being sad ;)

**Comment by hyenadog** [comment] 2012-10-08 19:51
totally agree with you Guillaume .. thats why the raspi will sell in the millions and the A10 boards in the handfulls

**Comment by amery** [comment] 2012-10-08 20:00
since the 24th until today there aren't 21 days. also last week was holiday in china where the people who knows the internals of the A10 lives.

**Comment by guillaumef** [comment] 2012-10-08 20:12
https://github.com/amery/linux-allwinner/issues/40#issuecomment-8644865

The patch given on the ML is as usefull as mine. It's a piece of test code without any comment and filled of useless statements.
At least, while waiting for the revelation from China, a pre-patch correcting the issue by disabling the VersC switch could have been post as a temporary solution and it could have been a wise decision for the community.

PS: Sorry for being sad.

**Comment by amery** [comment] 2012-10-15 08:39
can this ticket be closed? or some still have troubles?

**Comment by amery** [comment] 2012-10-30 21:22
then I'll assume it's fixed and close the ticket

**Closed as completed by amery** 2012-10-30 21:22 UTC
Labels: 3.0-v2, sata, bug

**Comment by sfrappier** [comment] 2013-02-18 18:27
techn referenced the issue that I reported regarding the Hackberry A10 board (and referenced it in the thread) - let me know how I can help as I reported the issue with the Hackberry and also referenced the commit in Issue 113 that addresses the hard-lock condition.

**Comment by plhua** [comment] 2013-02-20 06:31
encounter same issue 113 on cubieboard. I just want XBMC run with my HDD. hope this would be fixed soon.
