### ISSUE TITLE
linux-sunxi-3.4: Kernel OOPS while connecting an USB HDD to USB OTG

### ISSUE THREAD

**Issue by apxii** [linux-sunxi/linux-sunxi#85] opened 2012-10-13 11:07 UTC
Kernel faults when USB hard drive is connected.

[  227.210000] usb 1-1: new high-speed USB device number 2 using sw_hcd_host0
[  227.220000] Unable to handle kernel NULL pointer dereference at virtual address 00000000
[  227.220000] pgd = c0004000
[  227.220000] [00000000] *pgd=00000000
[  227.220000] Internal error: Oops: 817 [#1] PREEMPT ARM
[  227.220000] Modules linked in: nls_ascii nls_cp866 vfat fat disp_ump autofs4 mali_drm drm mali ump 8192cu
[  227.220000] CPU: 0    Not tainted  (3.4.12-apx6+ #4)
[  227.220000] PC is at __raw_writesl+0x44/0xd4
[  227.220000] LR is at sw_hcd_write_fifo+0xd0/0xf0
[  227.220000] pc : [<c020ab2c>]    lr : [<c02d9db0>]    psr: 60000093
[  227.220000] sp : ef0c9c78  ip : 00400000  fp : ef0c9c9c
[  227.220000] r10: 00000000  r9 : ed02df40  r8 : f1c13000
[  227.220000] r7 : 00000000  r6 : 00000008  r5 : ef0ca598  r4 : ed02de40
[  227.220000] r3 : 01000680  r2 : 00000000  r1 : ed02de48  r0 : 00000000
[  227.220000] Flags: nZCv  IRQs off  FIQs on  Mode SVC_32  ISA ARM  Segment kernel
[  227.220000] Control: 10c5387d  Table: 6eb5c019  DAC: 00000015

Full dmesg is at http://pastebin.com/WMBHpFqB

Board is an MK802 with 1G memory.

**Comment by polarcat** [comment] 2012-10-13 13:35
From the dmesg output you have supplied I have noticed that you run some 3.4.12-apx6+ kernel, may we see your sun4i_defconfig? The thing is that I tried to reproduce this bug using version 3.4.12+ built from sunxi-3.4 (former linux-sunxi-3.4) + sun4i_defconfig and the usb hdd I happen to have on my table does not cause any problems. The hardware is mk802 with 1GB.

**Comment by apxii** [comment] 2012-10-13 13:59
My .config is at http://pastebin.com/HVkup5Q9

I also have some changes is kernel (all in rtl8912cu driver):
Allow the driver to compile:
https://github.com/apxii/linux/commit/7fea174bba3b5852618a17d9cc64dc9b44dbcfdb
and disable debug messages that fills up dmesg quickly
https://github.com/apxii/linux/commit/ffdeaf7183f3066df142beb149e43260125579ef

**Comment by amery** [comment] 2012-10-13 15:08
please try disabling `CONFIG_USB_GADGET`, that's known to be broken (#29)

**Comment by apxii** [comment] 2012-10-13 17:30
No, doesn't help.
And it is not builds with CONFIG_USB_GADGET=N without applying a patch at:
https://github.com/apxii/linux/commit/ef35138cacaf00cb9a1efc42333a42155ebb5a11
Please, apply it. Probably it is related with issue #83

**Comment by apxii** [comment] 2012-10-13 17:37
I had enabled debug messages in sun4i_usb with https://github.com/apxii/linux/commit/32c06c2204fe947807af2cd2ff815df2fbbca308
New dmesg is at http://pastebin.com/b2yL2dRs

**Comment by polarcat** [comment] 2012-10-13 20:37
i was not able to reproduce the problem using your config in combination with git://github.com/linux-sunxi/linux-sunxi branch sunxi-3.4: USB HDD is detected and mounted successfully. Does this combination work for you too?

**Comment by apxii** [comment] 2012-10-14 08:37
@polarcat, just to be curious, what is your's u-boot configuration and script.bin file?
My MK802 works only if I set memory map in u-boot as 2 banks of 512M, otherwise there is no video output.
And probably we have different hardware, USB error is always there.
Can you post somewhere your kernel build and u-boot?

**Comment by polarcat** [comment] 2012-10-14 09:49
please try this https://raw.github.com/polarcat/share/master/mk802-boot.tar

**Comment by apxii** [comment] 2012-10-14 10:35
@polarcat No. Same error. It not boots to X because of modules' absence, but it doesn't matter.

_not relevant to this thread, byt may help_
It looks like bad memory confuguration or bug somewhere in USB code, since when I trying to use rtl8192cu module it falls with this error:
[  159.230000] kernel BUG at /media/254/Allwinner/linux/arch/arm/include/asm/dma-mapping.h:321!
[  159.230000] Internal error: Oops - BUG: 0 [#1] PREEMPT ARM
This is a assert on a bad physical address.

**Comment by polarcat** [comment] 2012-10-14 11:26
I really have no idea what to look for since on my device problem does not exist.. Any chance to capture dmesg output from the kernel i have sent? Could it be because we run different userspace? Later today I can try to share rootfs image that I am running (~400MB). Not sure how it will help, but perhaps we could understand whether we deal with hardware specific problem or not :)

**Comment by apxii** [comment] 2012-10-14 11:39
@polarcat Here it is: http://pastebin.com/CUewcjEP

**Comment by apxii** [comment] 2012-10-14 11:41
@polarcat And my MK802 is an MK802+, without AXP209 power controller, if it does matter.

**Comment by polarcat** [comment] 2012-10-14 15:57
>    [1]@polarcat Here it is: [2]http://pastebin.com/CUewcjEP

```
this one is still for your kernel,

Linux version 3.4.12-apx6+ (apx@mk802.lan)

mine would look like this,

Linux version 3.4.12-apx6+ (cat@cat)
```

**Comment by polarcat** [comment] 2012-10-14 15:59
>    [1]@polarcat And my MK802 is an MK802+, without AXP209 power
>    controller, if it does matter.

```
Mine mk802 does not have AXP neither, and for some reason
I believe that it does not really matter :)
```

**Comment by apxii** [comment] 2012-10-14 16:02
14.10.2012, 19:57, "Aliaksei Katovich" notifications@github.com:

> > [1]@polarcat Here it is: [2]http://pastebin.com/CUewcjEP
> 
> this one is still for your kernel,
> 
> Linux version 3.4.12-apx6+ (apx@mk802.lan)
> 
> mine would look like this,
> 
> Linux version 3.4.12-apx6+ (cat@cat)

It is cat@cat version, look at string 39

## 

Андрей

**Comment by polarcat** [comment] 2012-10-14 16:04
@apxii oops, indeed, sorry, i was studying log from different tab ;)

**Comment by polarcat** [comment] 2012-10-14 17:54
@apxii I have noticed some difference in logs, look

from mine device: when i attach harddrive kernel prints following

usb 2-1: new high-speed USB device number 2 using sw-ehci

and kernel never ends up in calling sw_hcd_write_fifo() hence does not panic but instead sees the disk

from your device: when you plug harddisk following log entry is seen

usb 1-1: new high-speed USB device number 2 using sw_hcd_host0

then sw_hcd_write_fifo() is called after which kernel oopses.

I wonder, why is that difference?..

**Comment by apxii** [comment] 2012-10-14 18:13
I'm inserting disk in OTG port and keyboard/mouse in a port nearby a power jack.

**Comment by hno** [comment] 2012-10-14 18:45
sön 2012-10-14 klockan 03:35 -0700 skrev Андрей Панов:

> @polarcat No. Same error. It not boots to X because of modules'
> absence, but it doesn't matter.

How are you booting? Which bootloader? And from NAND or SD?

Regards
Henrik

**Comment by polarcat** [comment] 2012-10-14 18:46
@apxii Ah, that explains. And obviously you are using DC power supply. My setup is different: I use host connector to plug all peripherals and power device via otg port. So, as a workaround for your problem would be using host connector :)

**Comment by apxii** [comment] 2012-10-14 18:54
@hno I'm booting from SD with u-boot confugured for Cubieboard with 1G RAM and changed to report 2 of 512M memory banks.

**Comment by polarcat** [comment] 2012-10-14 19:03
@apxii i tried to connect harddrive via OTG and got same oops. Still, my recommendation would be to use HOST connector only (+usb hub in case of multiple peripherals). As amery explained, OTG stuff is not quite working in sunxi, though this connector is good for supplying power into mk802.

**Comment by apxii** [comment] 2012-10-14 19:03
@polarcat Or set CONFIG_SW_SUN4I_USB=N and made sw-ehci handle all USB ports. It should be not too hard.

**Comment by polarcat** [comment] 2012-10-14 19:04
yes, if you do not want to be able to power over usb. Or it is not the case?

**Comment by polarcat** [comment] 2012-10-14 19:10
@apxii AFAIK CONFIG_SW_SUN4I_USB is not set in sun4i_defconfig.

**Comment by apxii** [comment] 2012-10-14 19:11
@polarcat Oh, I meant CONFIG_USB_SW_SUN4_USB

**Comment by polarcat** [comment] 2012-10-14 19:13
@apxii neither that is ;)

**Comment by polarcat** [comment] 2012-10-14 19:14
@apxii you probably meant CONFIG_USB_SW_SUN4I_HCD0?

**Comment by apxii** [comment] 2012-10-14 19:14
@polarcat Yes. CONFIG_USB_SW_SUN4I_USB.

**Comment by polarcat** [comment] 2012-10-14 19:17
@apxii ah, there was typo in the first case so grep did not show me anything.

**Comment by apxii** [comment] 2012-10-14 19:23
@polarcat Sorry

**Comment by apxii** [comment] 2012-10-14 19:27
@polarcat And there was a dependency in Kconfig than don't allow having just sw-ehci driver without USB manager.
this patch changes this
https://github.com/apxii/linux/commit/5710f82a012ab175a64a66b094d7de1c08e41abb
and I'll try tomorrow to have all USB ports handled by sw-ehci driver

**Comment by amery** [comment] 2012-12-12 22:51
hi, can you see if this is fixed now?

**Comment by apxii** [comment] 2012-12-13 05:25
13.12.2012 2:51, Alejandro Mery пишет:

> hi, can you see if this is fixed now?
> 
> Yes, it works!

And just one cosmetic change. For unknown reason OTG port is registered 
as USB 1.1, and actually it is 2.0.
This will fix it:
https://github.com/apxii/linux/commit/9a67fc2a9da197380da484f18794ad23774771a2

It looks previously it was 2.0, but someone changed it to 1.1 at some point.

## 

```
     Андрей
```

**Comment by amery** [comment] 2012-12-13 11:46
@apxii can you submit the patch for the flag part to the linux-sunxi mailing list?

I'm closing this now that f70df06d04c8ec3637e678d0a32659997fa3fed9 is confirmed to fix the issue. Thanks!

**Closed as completed by amery** 2012-12-13 11:46 UTC
Labels: bug, 3.4, usb
