### ISSUE TITLE
USB device mode do not work

### ISSUE THREAD

**Issue by YuukiHogo** [linux-sunxi/linux-sunxi#76] opened 2012-09-14 11:07 UTC
In branch `allwinner-v3.0-android-v2` USB gadget modules `modprobe` without issues, but usbc do not switch controller to client mode - upon connection to USB host it doesn't detect anything.
dmesg:

```
[  613.650000] ------------IRQ DISCONNECT-------------
[  613.650000] 
[  613.660000] usb 1-1: USB disconnect, device number 2
[  613.760000] [sw_hcd]: sw_hcd_h_disable, epnum = 0
[  613.760000] [sw_hcd]: sw_hcd_h_disable, epnum = 0
[  613.790000] [sw_hcd]: sw_hcd_h_disable, epnum = 1
[  613.790000] [sw_hcd]: sw_hcd_h_disable, epnum = 82
[  613.870000] 
[  613.870000] 
[  613.870000] rmmod_host_driver
[  613.870000] 
[  613.870000] [sw_hcd0]: sw_usb_host0_disable start
[  613.870000] -------sw_hcd0_soft_disconnect---------
[  613.870000] [sw_hcd_host0]: Set USB Power OFF
[  613.870000] sw_hcd_stop: sw_hcd disabled
[  613.940000] [sw_hcd0]: close_usb_clock
[  613.940000] [sw_hcd0]: sw_usb_host0_disable end
[  678.370000] survey done event(b)
[  678.540000] [sw_udc]: [sw_usb_udc]: binding gadget driver 'g_serial'
[  678.550000] [sw_udc]: alloc request: ep(0xc076de00, ep0, 64), req(0xe690ef00)
[  678.560000] gserial_setup: registered 1 ttyGS* device
[  678.560000] g_serial gadget: adding config #2 'CDC ACM config'/bf18b3a8
[  678.570000] g_serial gadget: adding 'acm0'/e72a2f00 to config 'CDC ACM config'/bf18b3a8
[  678.580000] ep_matches, wrn: endpoint already claimed, ep(0xc076de40, 0xe690ee00, ep1-bulk)
[  678.600000] ep_matches, wrn: endpoint already claimed, ep(0xc076de40, 0xe690ee00, ep1-bulk)
[  678.600000] ep_matches, wrn: endpoint already claimed, ep(0xc076de80, 0xe690ee00, ep2-bulk)
[  678.620000] 3333333
[  678.620000] 3333333
[  678.620000] [sw_udc]: alloc request: ep(0xc076df40, ep5-int, 512), req(0xe68e2980)
[  678.620000] g_serial gadget: acm ttyGS0: dual speed IN/ep1-bulk OUT/ep2-bulk NOTIFY/ep5-int
[  678.640000] g_serial gadget: cfg 2/bf18b3a8 speeds: high full
[  678.640000] g_serial gadget:   interface 0 = acm0/e72a2f00
[  678.640000] g_serial gadget:   interface 1 = acm0/e72a2f00
[  678.660000] g_serial gadget: Gadget Serial v2.4
[  678.660000] g_serial gadget: g_serial ready
[  701.810000] 
[  701.810000] 
[  701.810000] insmod_device_driver
[  701.810000] 
[  701.810000] [sw_udc]: sw_usb_device_enable start
[  701.810000] [sw_udc]: usb_vbase  = 0xf1c13000
[  701.810000] [sw_udc]: sram_vbase = 0xf1c00000
[  701.830000] [sw_udc]: open_usb_clock
[  701.870000] [sw_udc]: usbd_stop_work
[  701.870000] [sw_udc]: sw_usb_device_enable end
```

**Comment by amery** [comment] 2012-09-15 10:03
what defconfig?

**Comment by YuukiHogo** [comment] 2012-09-16 20:49
Using sun4i_defconfig with gadget-related modules.

**Comment by amery** [comment] 2012-09-16 20:53
can you try with sun4i_crane_defconfig instead? Most of the gadget integration Allwinner did is sadly dependent on Android.

**Comment by YuukiHogo** [comment] 2012-09-17 10:07
Just tried it. Hangs at

```
Starting kernel ...
```

and often self-reboots right after this message. No success boot until now with this config.

**Comment by YuukiHogo** [comment] 2012-09-25 10:07
I made it to boot to user-space using sun4i_crane_defconfig. Plugging it to host device makes no log entries on host, although on device side there still all same

```
[   59.750000] android_work: did not send uevent (0 0   (null))
[   70.860000] 
[   70.860000] 
[   70.860000] insmod_device_driver
[   70.860000] 
[   70.860000] [sw_udc]: sw_usb_device_enable start
[   70.860000] [sw_udc]: usb_vbase  = 0xf1c13000
[   70.860000] [sw_udc]: sram_vbase = 0xf1c00000
[   70.860000] [sw_udc]: open_usb_clock
[   70.920000] [sw_udc]: usbd_stop_work
[   70.920000] [sw_udc]: sw_usb_device_enable end
```

**Comment by YuukiHogo** [comment] 2012-09-27 09:54
OK. I found way to make it _seem_ to work. Dunno is it right or wrong way, but now at least host get a bunch of events and logs about USB device. And detects it correctly.

```
diff --git a/drivers/usb/sun4i_usb/udc/sw_udc.c b/drivers/usb/sun4i_usb/udc/sw_udc.c
index 28741a2..8a58989 100644
--- a/drivers/usb/sun4i_usb/udc/sw_udc.c
+++ b/drivers/usb/sun4i_usb/udc/sw_udc.c
@@ -3279,7 +3279,7 @@ int sw_usb_device_enable(void)
                goto err;
        }

-       if(udc->driver && is_udc_enable){
+       if(udc->driver && !is_udc_enable){
                sw_udc_enable(udc);
                cfg_udc_command(SW_UDC_P_ENABLE);
        }
```

**Comment by amery** [comment] 2012-09-27 09:57
@YuukiHogo can you check you have that usb controller enabled in your script.bin?

**Comment by YuukiHogo** [comment] 2012-09-27 11:03
evb.bin and script.bin was taken from NAND with Android where USB device mode seems to work.
`evb.bin`:

```
[usbc0]
usb_used = 1
usb_port_type = 2
usb_detect_type = 1
usb_id_gpio = port:PH04<0><1><default><default>
usb_det_vbus_gpio = port:PH05<0><0><default><default>
usb_drv_vbus_gpio = port:PB09<1><0><default><0>
usb_host_init_state = 0

[usbc1]
usb_used = 0
usb_port_type = 1
usb_detect_type = 0
usb_id_gpio =
usb_det_vbus_gpio =
usb_drv_vbus_gpio = port:PH06<1><0><default><0>
usb_host_init_state = 1

[usbc2]
usb_used = 1
usb_port_type = 1
usb_detect_type = 0
usb_id_gpio =
usb_det_vbus_gpio =
usb_drv_vbus_gpio = port:PH12<1><0><default><0>
usb_host_init_state = 0
```

I think usbc2 is a link to rtl8192cu WiFi module.

**Comment by YuukiHogo** [comment] 2012-09-27 11:20
Changing usb_used to 1 in [usbc1] section doesn't makes difference.

**Comment by YuukiHogo** [comment] 2012-09-27 11:28
Value of `is_udc_enable` changes only in `sw_udc_set_pullup()` but it never fires up. It all ends in `struct usb_gadget_ops` with `.pullup` and `.vbus_session` members those never fire up also. Can't get which driver must call them...

**Comment by YuukiHogo** [comment] 2012-09-29 11:43
OK. Simply changing init value of `is_udc_enable` to 1 almost solves initial issue. I think reverting changes related to `drivers/usb/sun4i_usb/udc/sw_udc.c` made by 93842453763f63fbab41875189aa76cf9a145e35 must solve that issue completely.

But there come one more issue. When I use any gadget module - it basically works with Unix-based OSes (Linux & Mac OS X 10.6) but fails with OS Windows with code 10 during driver installation. Sniffing USB shows incomplete initialization without any endpoints on host Windows PC. Looks like something goes wrong during GET_DESCRIPTOR phase when host PC run Windows. On Linux host PC (according sysfs) endpoints appear correctly (i.e. for g_zero gadget there are two endpoints).

Will try to go deeper...

**Comment by techn** [comment] 2012-09-29 13:22
Hi,

Would this commit help?
https://github.com/amery/linux-allwinner/commit/4dfaa32c8997b0ada87de45d5b8003bc94348373

-Jari

2012/9/29 YuukiHogo notifications@github.com

**Comment by YuukiHogo** [comment] 2012-09-29 13:47
Seems HEAD already has it applied to sun4i_usb...

**Comment by cloud-rocket** [comment] 2012-09-29 22:17
I tried changing initial value of is_udc_enable to 1, but it makes no difference - gadget drivers mention that controller is not loaded, I tried g_file_storage or g_hid (sw_udc.c throws "ERR: usb device is not active" error when trying to insmod gadget driver)

I also tried to switch OTG port to device only (using menuconfig), but in this case kernel has compilation errors....
I use 3.0.36 (crane config), any ideas?
Meir Tseitlin

**Comment by RobVanDerHoeven** [comment] 2012-10-01 10:15
I did some browsing of the kernel source and found this function in usbc.c

``` c
void USBC_OTG_SelectMode(__hdle hUSB, __u32 mode)
{
    __usbc_otg_t *usbc_otg = (__usbc_otg_t *)hUSB;

    if(usbc_otg == NULL){
        return ;
    }

    if(mode == USBC_OTG_HOST){

    }else{

    }
}
```

Maybe this is part of the problem?

**Comment by YuukiHogo** [comment] 2012-10-01 10:56
As **meirts** said:

> I tried changing initial value of is_udc_enable to 1, but it makes no difference - gadget drivers mention that controller is not  loaded, I tried g_file_storage or g_hid (sw_udc.c throws "ERR: usb device is not active" error when trying to insmod gadget driver)
> 
> I also tried to switch OTG port to device only (using menuconfig), but in this case kernel has compilation errors....
> I use 3.0.36 (crane config), any ideas?

`sun4i_crane_defconfig` works with only one gadget driver and defaults to `android_usb` build-in module. So you need to switch it to another in .config (i.e. by `$ make menuconfig`). There is no way to `# insmod` gadget driver with `sun4i_crane_defconfig` because USB device controller is busy with built-in gadget module.

**Comment by amery** [comment] 2012-10-01 11:02
alaihs the gadget code is heavily bound to android (even inside android.c!) so it's on the list of "needs to be rewritten" :<

**Comment by YuukiHogo** [comment] 2012-10-01 11:31
Only `android.c` (which is `android_usb`) is bound to android infrastructure. Dunno why there is need to rewrite android_usb. Can't see a point to use it without android...

**Comment by amery** [comment] 2012-10-01 11:34
but iirc there is where they injected the 'allwinnerization' code which we might need to move to a sunxi.c or so. But I haven't had time to look there in detail yet so I could be totally wrong.

**Comment by amery** [comment] 2012-10-01 11:38
anyhow, can we move this to the mailing list? 
- http://linux-sunxi.org/Mailing_list
- https://groups.google.com/d/forum/linux-sunxi

**Comment by cloud-rocket** [comment] 2012-10-01 12:12
RobVanDerHoeven, USBC_OTG_SelectMode function is not called anywhere (and it is not system function as far as I know - so it is not important)

YuukiHogo, I know that UCD supports single gadget driver on top of it, but inside menuconfig you can preselect a driver (I tried putting serial or hid drivers instead of android) or compile it with no in-kernel driver and insmod one of the modules later (the injection procedure seems to be implemented). Anyway, I tried both ways and from my observation, the UDC device is not activated, so both cases are not working as a result of it.

amery, I am not sure android.c needs to be rewritten, because from my observation it is mostly related to adb and custom mass storage implementation. We just need to find out how to enable the UDC device.

I was inspecting their code for a little and I think that sw_udc.c::sw_usb_device_enable function needs to be called and it is not. 
The call stack should be:
sw_udc.c::sw_usb_device_enable
from  usb_msg_center.c::insmod_device_driver
usb_msg_center.c::do_usb_role_null
usb_msg_center.c::usb_msg_center

Observing dmesg log of android, these function are called when you attach usb host to the OTG port, but they are not when running ubuntu.

Interesting part is that I didn't find any traces of the relevant code inside android.c - so I think it is not related anyhow.

Ideas?

Also, let us know where are you willing to continue this conversation.

Meir

**Comment by amery** [comment] 2012-10-01 12:27
@meirts the allwinnerization chunk in android.c is added by 93842453763f63fbab41875189aa76cf9a145e35

**Comment by cloud-rocket** [comment] 2012-10-01 12:35
Sorry don't understand what is "allwinnerization chunk" and how is it related  :<

Isn't android.c just a gadget driver which suppose to load on top of UDC?

**Comment by amery** [comment] 2012-10-01 12:42
@meirts this code was written by Allwinner (who makes the chip, and who has the documentation) and for them android is _the_ goal, also `script.bin` (sys_config) is their wait to configure boards. integration and feature enabling is done via code like 93842453763f63fbab41875189aa76cf9a145e35, where they decide to enable OTG or not.

**Comment by YuukiHogo** [comment] 2012-10-01 12:53
@meirts I think it is related to UDC initialization. Check `script.bin` and try to use `*_defconfig`. Also it is not seems gadget-related issue. Similar to mine it is related to UDC code and HCD.

**Comment by cloud-rocket** [comment] 2012-10-01 12:55
Yep, I know that their goal is android and that android.c is written by Allwinner for this purpose only. But I still can't figure out how to enable OTG device support inside sun4i_usb (which seems like regular linux usb controller driver written by Allwinner and knows hwo to work with just a single gadget on top of it). 
As far as I understand android.c contains gadget only functionality.

android.c contains calls to usb_gadget_connect (strange function I don't recognize), after usb_add_config (which is standard Gadget API function)....

Maybe this is the missing point?

**Comment by cloud-rocket** [comment] 2012-10-01 12:59
YuukiHogo, my device is Mini X and it works with crane config only. It uses evb.bin and I checked it already - seems all ok there:

[usbc0]
usb_used = 1
usb_port_type = 2
usb_detect_type = 1
usb_id_gpio = port:PH04<0><1><default><default>
usb_det_vbus_gpio = port:PH05<0><0><default><default>
usb_drv_vbus_gpio = port:PB09<1><0><default><0>
usb_host_init_state = 0

**Comment by YuukiHogo** [comment] 2012-10-01 13:05
Why it doesn't work with `sun4i_defconfig`? I think it must to work with both types.

**Comment by amery** [comment] 2012-10-01 13:07
as I told you. USB gadget/slave support assumes android and this dependency is assumed all over the code.

**Comment by YuukiHogo** [comment] 2012-10-01 13:37
Anyway I have identical issue with sun4i_defconfig and sun4i_crane_defconfig.

**Comment by cloud-rocket** [comment] 2012-10-01 13:42
So maybe we can solve it by creating a C file with few functions which will be called from standard gadget drivers (g_ether, g_serial), which will do the mandatory functionality from android.c (like initializing the device). 

amery, can you be more specific about the dependency you found? Is it only inside android.c? Can you provide function calls?

**Comment by amery** [comment] 2012-10-01 13:50
my idea was to move all allwinner code in gadget to a sunxi.c module, but haven't looked deeper on that. It's only from the impression/frustration trying to forward this part of the 3.4 branch. some more details at #29. but @meirts, please join @YuukiHogo on the mailing list. you both seem like the right people to fix this subsystem ;-)

patches welcomed! but keep in mind we need to preserve script.bin and android support as well... but in the right places so linux support works :<

**Comment by RobVanDerHoeven** [comment] 2012-10-01 14:37
@meirts

You are absolutely right, the USBC_OTG_SelectMode function is not called anywhere. Can anyone point me to the location where the usb _hardware_ is switched from host-mode to device-mode? I cannot find it.

**Comment by amery** [comment] 2012-10-01 14:50
@RobVanDerHoeven on the mailinglist please https://groups.google.com/d/topic/linux-sunxi/sEecvR_8KKk/discussion :-)

**Comment by cloud-rocket** [comment] 2012-10-01 14:51
RobVanDerHoeven, 

my impression is that usb_msg_center.c::do_usb_role_null is doing it - 
I think that this code should be called when you insert device/host into usb (USB interrupt), but in my case it never called

(we are moving this conversation to here: https://groups.google.com/forum/#!topic/linux-sunxi/sEecvR_8KKk)

**Comment by amery** [comment] 2012-12-12 22:51
hi, can you see if this is fixed now?

**Comment by YuukiHogo** [comment] 2012-12-13 09:53
It still malfunctioning on my devices with

sw_udc.c:56

```
static u8 is_udc_enable = 0;   /* is udc enable by gadget? */
```

Defaulting it to 1 makes it usable.

**Comment by amery** [comment] 2012-12-21 12:27
hi, can you give a try using the stage/sunxi-3.0 branch?

**Comment by YuukiHogo** [comment] 2012-12-21 15:12
Just tried. Same behavior. Device completely ignores connection to host.

**Comment by amery** [comment] 2013-01-09 11:25
@YuukiHogo as it's a VERY intrusive change for a problem that only you seem to have, please submit it to the linux-sunxi mailing list where the sunxi-usb "team" can see it, comment and suggest a proper solution.

**Closed as completed** 2013-04-10 10:37 UTC
Labels: 3.0-v2, usb

**Comment by IDmedia** [comment] 2014-12-29 00:36
I'm having the same issue. Has this issue been resolved?
Host mode works, but not switching to client/OTG mode. I'm on kernel version 3.4 (using BananaPi).

Output from dmesg:

<pre>
[   86.631328] sd 2:0:0:0: [sda] Attached SCSI removable disk
[  108.515479] WRN:L2728(drivers/usb/sunxi_usb/udc/sw_udc.c):ERR: usb device is not active
[  108.523868] usb open backing file: /dev/sda, 0xeeb99800
[  108.530182] g_mass_storage gadget: Mass Storage Function, version: 2009/09/11
[  108.541530] g_mass_storage gadget: Number of LUNs=1
[  108.550433]  lun0: LUN: removable file: /dev/sda
[  108.562358] ep_matches, wrn: endpoint already claimed, ep(0xc08f406c, 0xbf02528c, ep1-bulk)
[  108.568320] g_mass_storage gadget: Mass Storage Gadget, version: 2009/09/11
[  108.581626] g_mass_storage gadget: userspace failed to provide iSerialNumber
[  108.593200] g_mass_storage gadget: g_mass_storage ready
[  108.602686] WRN:L2762(drivers/usb/sunxi_usb/udc/sw_udc.c):ERR: usb device is not active
</pre>

**Comment by joyhope** [comment] 2015-06-03 09:42
I have the similar problem in kernel version 3.4.103 (using BananaPro)

> root@lemaker:~# WRN:L2728(/home/bananapi/bananapi/lemaker-bsp/linux->sunxi/drivers/usb/sunxi_usb/udc/sw_udc.c):ERR: usb device is not active
> ep_matches, wrn: endpoint already claimed, ep(0xc08f7fbc, 0xede54a00, ep1-bulk)
> ep_matches, wrn: endpoint already claimed, ep(0xc08f7fbc, 0xede54a00, ep1-bulk)
> ep_matches, wrn: endpoint already claimed, ep(0xc08f8008, 0xede54a00, ep2-bulk)
> <6>g_serial gadget: Gadget Serial v2.4
> <6>g_serial gadget: g_serial ready
> WRN:L2762(/home/bananapi/bananapi/lemaker-bsp/linux->sunxi/drivers/usb/sunxi_usb/udc/sw_udc.c):ERR: usb device is not active

Whether the issue is solved?

**Comment by strelec** [comment] 2015-12-10 17:47
Damn, the only reason I went with the more expensive Banana PI was the OTG capability.

Now, it doesn't even work. Huge disappointment! Is this being worked on? Why is the bug closed if it is not fixed?

**Comment by EduardMe** [comment] 2015-12-30 23:48
I got the android composite driver working. All kinds of gadgets can be loaded into it (check under /sys/class/android_usb/android0/functions):

```
# 1 = host role, 2 = device role
echo 1 > /sys/bus/platform/devices/sunxi_usb_udc/otg_role
echo 2 > /sys/bus/platform/devices/sunxi_usb_udc/otg_role

echo 0 > /sys/class/android_usb/android0/enable
echo 1d6b > /sys/class/android_usb/android0/idVendor
echo 0001 > /sys/class/android_usb/android0/idProduct
echo mtp > /sys/class/android_usb/android0/functions
echo 1 > /sys/class/android_usb/android0/enable
```

HID for example is detected on a host in my tests. Others need to be configured. Worked on the OrangePI PC, maybe it helps for BananaPI.

**Comment by lauraruoyun** [comment] 2016-09-09 22:10
Hi, has someone find the solution for the problem reported in 2012 : When I use any gadget module - it basically works with Unix-based OSes (Linux & Mac OS X 10.6) but fails with OS Windows with code 10 during driver installation. Sniffing USB shows incomplete initialization without any endpoints on host Windows PC. Looks like something goes wrong during GET_DESCRIPTOR phase when host PC run Windows. On Linux host PC (according sysfs) endpoints appear correctly (i.e. for g_zero gadget there are two endpoints). We're in 2016, I have exactly the same problem, I use Orange PI Lite with Kernel Linux Sunxi 3.4. Can anyone help? Thanks!
