### ISSUE TITLE
sunxi-3.0 make ... -C kernel-dir does not work any more

### ISSUE THREAD

**Issue by MarcusSt** [linux-sunxi/linux-sunxi#90] opened 2012-10-25 19:20 UTC
As already in the title, make with -C kernel-dir does not work any more, as the mali driver will look for files in the current working directory rather than the kernel root.

marcus@linux:~/mk802/linux-sunxi$ make mrproper
/home/marcus/mk802/linux-sunxi/drivers/gpu/mali/mali/Kbuild:59: "CONFIG_TRACEPOINTS required for USING_PROFILING"
marcus@linux:~/mk802/linux-sunxi$ cd ..
marcus@linux:~/mk802$ make mrproper -C linux-sunxi/
make: Entering directory `/home/marcus/mk802/linux-sunxi'
/home/marcus/mk802/linux-sunxi/drivers/gpu/mali/mali/Kbuild:48: "USING_PROFILING not supported, disabling."
gcc: error: /home/marcus/mk802/drivers/gpu/mali/mali/arch/config.h: No such file or directory
gcc: fatal error: no input files
compilation terminated.
[...]
make: Leaving directory`/home/marcus/mk802/linux-sunxi'
marcus@linux:~/mk802$

**Comment by amery** [comment] 2012-10-26 11:39
can you try on `stage/sunxi-3.0`? at least when using `O=` I can't reproduce it. will make a test tree now to test without `O=`

**Comment by amery** [comment] 2012-10-26 13:20
ok, reproducted.

**Comment by rzk** [comment] 2012-11-02 07:04
`CONFIG_TRACEPOINTS required for USING_PROFILING`
Can be fixed with simple patch I've sent to ML. We dont use profiling anyway.

**Closed as completed** 2012-11-07 23:03 UTC

**Comment by amery** [comment] 2012-11-07 23:08
both things should be fixed now
