### ISSUE TITLE
SATA problem on MeleA1000

### ISSUE THREAD

**Issue by nik0** [linux-sunxi/linux-sunxi#41] opened 2012-06-19 13:22 UTC
I succeeded to compile and start my own kernel, using the branch allwinner-v3.0-
android-v2 ...
But when I install the sata module (sw_ahci_platform) I have this error:

<6>ata1: EH complete
<3>ata1: exception Emask 0x10 SAct 0x0 SErr 0x4000000 action 0xe frozen
ata1: exception Emask 0x10 SAct 0x0 SErr 0x4000000 action 0xe frozen
<3>ata1: irq_stat 0x00000040, connection status changed
<3>ata1: SError: { DevExch }
<4>ata1: limiting SATA link speed to 1.5 Gbps
<6>ata1: hard resetting link
<6>ata1: SATA link down (SStatus 1 SControl 310)
<6>ata1: EH complete
<3>ata1: exception Emask 0x10 SAct 0x0 SErr 0x4000000 action 0xe frozen
<3>ata1: irq_stat 0x00000040, connection status changed
<3>ata1: SError: { DevExch }

I checked the internet, some guys report a cable error, but when I boot on 
Android I get this:

sw_ahci sw_ahci.0: controller can't do PMP, turning off CAP_PMP
sw_ahci sw_ahci.0: forcing PORTS_IMPL to 0x1
sw_ahci sw_ahci.0: AHCI 0001.0100 32 slots 1 ports 3 Gbps 0x1 impl platform mode
sw_ahci sw_ahci.0: flags: ncq sntf pm led clo only pio slum part ccc 
scsi0 : sw_ahci_platform
ata1: SATA max UDMA/133 irq_stat 0x00400040, connection status changed irq 56
ata1: SATA link up 3.0 Gbps (SStatus 123 SControl 300)
ata1.00: native sectors (2) is smaller than sectors (1953525168)
ata1.00: ATA-8: ST1000LM024 HN-M101MBB, 2AR10002, max UDMA/133
ata1.00: 1953525168 sectors, multi 0: LBA48 NCQ (depth 31/32)
ata1.00: configured for UDMA/133

Any suggestions ?

thanks and regards,

Nik0

**Comment by amery** [comment] 2012-06-19 13:23
dupe of #40

**Closed as completed by amery** 2012-06-19 13:23 UTC
Labels: 3.0-v2, sata, bug, dupe
