### ISSUE TITLE
Kernel panic with preempted kernel

### ISSUE THREAD

**Issue by davidgiven** [linux-sunxi/linux-sunxi#58] opened 2012-07-19 22:11 UTC
If I try to run any kernel with kernel preemption available, I get assorted peculiar crashes, most looking like this:

```
<1>Unable to handle kernel NULL pointer dereference at virtual address 00000019
<1>pgd = c0004000
<1>[00000019] *pgd=00000000[    3.050000] [00000019] *pgd=00000000
<0>Internal error: Oops: 5 [#1] PREEMPT
<d>Modules linked in:[    3.060000] Modules linked in:
CPU: 0    Not tainted  (3.0.31+ #1)
PC is at regulator_get_voltage+0x10/0x3c
LR is at sun4i_cpufreq_initcall+0xb4/0x12c
pc : [<c02ae9f0>]    lr : [<c000ecf4>]    psr: a0000013
sp : db83bf58  ip : db83bf70  fp : db83bf6c
r10: 00000000  r9 : 00000000  r8 : 00000000
r7 : 00000013  r6 : 00000000  r5 : db83a000  r4 : ffffffed
r3 : 00000000  r2 : 00000000  r1 : 00000001  r0 : ffffffed
Flags: NzCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment kernel
```

(followed by lots of stuff that I can paste if it's useful)

If I turn kernel preemption off --- I usually go for server mode, with no forced preemption --- it works fine (although with diverse other issues). When it crashes, it usually happens some time during startup, although the exact place can vary. In other words, exactly like what it looks like: some code that's failing to handle kernel preemption properly, so a preemption request in the wrong place is causing a panic.

It's not just my kernels. I've just tried the prebuild SD card image at http://www.cnx-software.com/2012/06/22/ubuntu-12-04-server-armhf-image-for-mele-a1000a2000 and it behaves in precisely the same way.

I'm really confused. This is obviously working out-of-the-box for other people, yet for me it's crashing almost instantly on startup... and I'm not the only one, as I found this pastebin log:

http://pastebin.com/j6RXb0Ae

...which is word-for-word what I'm getting, even to the addresses! But I have no idea who posted it.

**Comment by davidgiven** [comment] 2012-07-19 22:12
It suddenly occurs to me: are there multiple revisions of Mele A1000 hardware? Mine says AB10-G32-V1.20-2 on the motherboard, if that helps.

**Comment by amery** [comment] 2012-07-19 22:47
can you load your image in gdb and tell me what `list *(sun4i_cpufreq_initcall+0xb4)` and `list *(regulator_get_voltage+0x10)` say?

**Comment by amery** [comment] 2012-07-19 22:47
also, on what branch was that `3.0.31+` built? can you try a newer build?

**Comment by cnxsoft** [comment] 2012-07-20 06:56
It looks like the crash that happens on MK802, but not Mele A1000.
I'd say it's a duplicate of Issue #46.

**Comment by amery** [comment] 2012-07-20 08:56
yes. I agree. this is a dupe of #46. can you try a cleanup patch in @turl's cpufreq branch? let's continue this in #46.

**Closed as completed** 2012-07-20 08:56 UTC
Labels: bug, dupe, cpufreq
