### ISSUE TITLE
Error during CHECK: userspace cannot reference function or variable defined in the kernel

### ISSUE THREAD

**Issue by romanrm** [linux-sunxi/linux-sunxi#67] opened 2012-08-20 07:26 UTC
Hello,

The kernel fails to compile for me with the following error. I used to workaround this by a dirty hack commenting out some lines in Makefile, but maybe there's a better way to fix this once and for all (and for everyone)?

---

...
  CHECK   include/asm-generic (34 files)
  CHECK   include/drm (13 files)
/mnt/src/server/usr/include/drm/drm_mode.h:85: found __[us]{8,16,32,64} type without #include <linux/types.h>
/mnt/src/server/usr/include/drm/i915_drm.h:120: found __[us]{8,16,32,64} type without #include <linux/types.h>
/mnt/src/server/usr/include/drm/mga_drm.h:260: found __[us]{8,16,32,64} type without #include <linux/types.h>
/mnt/src/server/usr/include/drm/radeon_drm.h:758: found __[us]{8,16,32,64} type without #include <linux/types.h>
/mnt/src/server/usr/include/drm/via_drm.h:117: found __[us]{8,16,32,64} type without #include <linux/types.h>
  CHECK   include/linux/byteorder (2 files)
  CHECK   include/linux/caif (2 files)
  CHECK   include/linux/can (4 files)
  CHECK   include/linux/dvb (8 files)
  CHECK   include/linux/hdlc (1 files)
  CHECK   include/linux/isdn (1 files)
  CHECK   include/linux/mmc (1 files)
/mnt/src/server/usr/include/linux/mmc/ioctl.h:10: found __[us]{8,16,32,64} type without #include <linux/types.h>
  CHECK   include/linux/netfilter/ipset (4 files)
  CHECK   include/linux/netfilter (69 files)
/mnt/src/server/usr/include/linux/netfilter/xt_socket.h:14: userspace cannot reference function or variable defined in the kernel
  CHECK   include/linux/netfilter_arp (2 files)
  CHECK   include/linux/netfilter_bridge (18 files)
  CHECK   include/linux/netfilter_ipv4 (14 files)
  CHECK   include/linux/netfilter_ipv6 (11 files)
  CHECK   include/linux/nfsd (6 files)
  CHECK   include/linux/raid (2 files)
  CHECK   include/linux/spi (1 files)
  CHECK   include/linux/sunrpc (1 files)
  CHECK   include/linux/tc_act (7 files)
  CHECK   include/linux/tc_ematch (4 files)
  CHECK   include/linux/usb (9 files)
  CHECK   include/linux/wimax (1 files)
  CHECK   include/linux (364 files)
/mnt/src/server/usr/include/linux/if_pppox.h:24: included file 'linux/if_pppolac.h' is not exported
/mnt/src/server/usr/include/linux/if_pppox.h:25: included file 'linux/if_pppopns.h' is not exported
/mnt/src/server/usr/include/linux/kernel.h:65: userspace cannot reference function or variable defined in the kernel
/mnt/src/server/usr/include/linux/kernel.h:97: userspace cannot reference function or variable defined in the kernel
/mnt/src/server/usr/include/linux/quota.h:175: userspace cannot reference function or variable defined in the kernel
/mnt/src/server/usr/include/linux/soundcard.h:1054: userspace cannot reference function or variable defined in the kernel
make[4]: **\* [/mnt/src/server/usr/include/linux/.check] Error 123
make[3]: **\* [linux] Error 2
make[2]: **\* [headers_check] Error 2
make[1]: **\* [deb-pkg] Error 2
make: **\* [deb-pkg] Error 2

**Comment by kenchy** [comment] 2012-08-20 18:46
Edit include/linux/Kbuild

Add:
header-y += if_pppolac.h
header-y += if_pppopns.h

Under:
header-y += if_pppox.h

And relax! HTH. This has been bugging me for ages, glad to have finally fixed it.

**Comment by romanrm** [comment] 2012-08-21 11:19
@amery can you perhaps look into adding this into your tree?

Also, any idea what is the cause of this issue, PPPoX is now somehow Allwinner-specific, or... wtf? :)

**Comment by kenchy** [comment] 2012-08-21 20:29
The Kbuild exports the headers. Hence without the export the error. Quite why these files are missing in the android tree, who knows.

**Comment by amery** [comment] 2012-08-22 07:09
@romanru I have very limited internet access until monday, can you poke another of those with commit access on the irc channel for it?

**Comment by romanrm** [comment] 2012-08-22 09:08
I don't think this warrants any hurry, and also I am not even sure what the proper fix should be.

**Comment by steev** [comment] 2012-08-22 13:39
I'll take a look this weekend when I (hopefully) get some spare time)

**Comment by amery** [comment] 2012-08-28 11:59
dupe of #17, but fixed with @kenchy's suggestion. see b4602a3ccff9989960ad7872c16128c9f48e8960

**Closed as completed by amery** 2012-08-28 11:59 UTC
Labels: Android, dupe
