### ISSUE TITLE
Upgrade Mali modules to DX910-SW-99002-r2p4-02rel0

### ISSUE THREAD

**Issue by turl** [linux-sunxi/linux-sunxi#30] opened 2012-05-26 19:33 UTC
My Android userspace libraries were r2p4-02rel0, so I upgraded the Mali kernel modules to DX910-SW-99002-r2p4-02rel0, as you can see in the following commit

https://github.com/allwinner-dev-team/linux-allwinner/commit/a8e8589499236ac2b0d5456bf2c9b275eee5235f

I've been using it a bit and it works fine.

NB: the commit also makes it the default release when building, previously r2p3 was the default.

**Comment by amery** [comment] 2012-05-27 10:44
I'm closing this ticket as a dupe of #19... I've added this commit to the `wip/allwinner-v3.0-android-v2/mali` branch.

can you try `DX910-SW-99002-r2p4-02rel1` to match the version in #19?

the goal is to have a single mali version, living in drivers/gpu/ and get rid of modules/mali/ entirely.

thanks!

**Closed as completed by amery** 2012-05-27 10:44 UTC
Labels: Android, 3.0-v2, mali, dupe
