### ISSUE TITLE
goodix_touch not work

### ISSUE THREAD

**Issue by haword** [linux-sunxi/linux-sunxi#78] opened 2012-09-16 11:47 UTC
In default configuration goodix not work.

**Comment by rzk** [comment] 2012-09-16 13:51
Please post more info about your problem: goodix_ts dmesg output, what system you use and etc. With just "that doesnt work" no one will be able to help you.

**Comment by amery** [comment] 2012-09-16 13:53
the related `dmesg` chunck from the original kernel is also needed to know what exact goodix_ts driver your device needs. we don't have them all.

**Comment by haword** [comment] 2012-09-16 15:14
dmesg
[   20.330000] ctp_detect: Detected chip Goodix-TS at adapter 2, address 0x55
[   20.340000] ===============================GT801 Probe===========================
[   20.340000] Begin goodix i2c test
[   20.340000] ===== goodix i2c test ok=======
[   20.350000] input: gt80x as /devices/virtual/input/input1
[   20.390000] ========goodix_init_panel=====default========
[   20.390000] ctp_set_irq_mode: config gpio to int mode. 
[   20.390000]  INTERRUPT CONFIG
[   20.390000] Read Goodix version
[   20.440000] init: Failed to create pty - disabling logging for job
[   20.450000] Goodix-TS 2-0055: GT80X Version: GT801_1R08_2011121501_Goodix_Tech  
[   20.450000] ========Probe Ok================
Xorg.0.log
[    25.772](II) config/udev: Adding input device gt80x (/dev/input/event1)
[    25.772](II) No input driver specified, ignoring this device.

if i run in terminal - cat /dev/input/event1 and press to screen, in the terminal will be nothing.
if i use kernel 3.0.8+ and drivers from miniand site, in terminal show random data when a press to screen.
if i compile kernel 3.0.8+ from branch lichee-3.0.8-sun4i, in the terminal will be nothing.

**Comment by rzk** [comment] 2012-09-16 21:15
Undefine multitouch support here https://github.com/amery/linux-allwinner/blob/allwinner-v3.0-android-v2/drivers/input/touchscreen/goodix_touch.h#L36 or, alternatively, install xserver-xorg-input-multitouch and configure multitouch support accordingly.

**Comment by amery** [comment] 2012-09-16 21:16
If that's it, we clearly need a CONFIG_ there

**Comment by haword** [comment] 2012-09-17 03:29
if  i undefine multitouch, xinput show device in list, but "cat /dev/input/event1" show nothing. in kernel 3.0.8+ from miniand multitouch defined and "cat /dev/input/event1" show random data where press to screen. when i compile kernel not show random data, when press to screen. I do not know, what can i do :(

**Comment by amery** [comment] 2012-09-17 06:31
ask your vendor for the sources so we can diff :-)

**Comment by amery** [comment] 2012-09-17 09:16
@haword above you pasted the related printk in the original kernel, can you show what our goodix_touch says? .. from the A13 SDK we got the goodix_ts 818 driver (see https://github.com/techn/linux-allwinner/commit/9fd591f17515de0d6672e3d0831e6fd06b11b2a2) but unfortunatelly there are many more and Goodix has ignored all requests for those drivers yet.

**Comment by amery** [comment] 2012-09-17 09:19
I'm closing this issue as it's a dupe of #26

**Closed as completed by amery** 2012-09-17 09:19 UTC
Labels: 3.0-v2, dupe
